#!/bin/csh
#
# File:    compilekcc
# Purpose: Used to compile/use Kylix with PC^2
# Author:  pc2@ecs.csus.edu
#
# Dependencies:  kcc
#
# $HeadURL: http://pc2.ecs.csus.edu/repos/pc2v9/branches/PC2_RELEASE_9_2_x/samps/scripts/compilekcc $
#

set mainfile=$1

#echo bc++ -A $mainfile
bc++ -A $mainfile

# eof $Id: compilekcc 2090 2010-04-10 19:28:54Z laned $ 
